// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "address", Type: field.TypeString, Size: 2147483647},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
	}
	// CustomerLicensesColumns holds the columns for the "customer_licenses" table.
	CustomerLicensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "license_code", Type: field.TypeString, Size: 2147483647},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "cpu", Type: field.TypeInt, Default: 0},
		{Name: "storage", Type: field.TypeInt, Default: 0},
		{Name: "number_of_nodes", Type: field.TypeInt, Default: 0},
		{Name: "customer_license_customer", Type: field.TypeInt, Nullable: true},
	}
	// CustomerLicensesTable holds the schema information for the "customer_licenses" table.
	CustomerLicensesTable = &schema.Table{
		Name:       "customer_licenses",
		Columns:    CustomerLicensesColumns,
		PrimaryKey: []*schema.Column{CustomerLicensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "customer_licenses_customers_customer",
				Columns:    []*schema.Column{CustomerLicensesColumns[8]},
				RefColumns: []*schema.Column{CustomersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LicensesColumns holds the columns for the "licenses" table.
	LicensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "duration", Type: field.TypeInt},
		{Name: "cpu", Type: field.TypeInt, Default: 0},
		{Name: "storage", Type: field.TypeInt, Default: 0},
		{Name: "number_of_nodes", Type: field.TypeInt, Default: 0},
		{Name: "customer_license_license", Type: field.TypeInt, Nullable: true},
	}
	// LicensesTable holds the schema information for the "licenses" table.
	LicensesTable = &schema.Table{
		Name:       "licenses",
		Columns:    LicensesColumns,
		PrimaryKey: []*schema.Column{LicensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "licenses_customer_licenses_license",
				Columns:    []*schema.Column{LicensesColumns[6]},
				RefColumns: []*schema.Column{CustomerLicensesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TodosColumns holds the columns for the "todos" table.
	TodosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"in_progress", "completed"}, Default: "in_progress"},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "todo_parent", Type: field.TypeInt, Nullable: true},
	}
	// TodosTable holds the schema information for the "todos" table.
	TodosTable = &schema.Table{
		Name:       "todos",
		Columns:    TodosColumns,
		PrimaryKey: []*schema.Column{TodosColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "todos_todos_parent",
				Columns:    []*schema.Column{TodosColumns[5]},
				RefColumns: []*schema.Column{TodosColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomersTable,
		CustomerLicensesTable,
		LicensesTable,
		TodosTable,
	}
)

func init() {
	CustomerLicensesTable.ForeignKeys[0].RefTable = CustomersTable
	LicensesTable.ForeignKeys[0].RefTable = CustomerLicensesTable
	TodosTable.ForeignKeys[0].RefTable = TodosTable
}
