// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thuanvh/golicenseserver/ent/customerlicense"
	"github.com/thuanvh/golicenseserver/ent/predicate"
)

// CustomerLicenseDelete is the builder for deleting a CustomerLicense entity.
type CustomerLicenseDelete struct {
	config
	hooks    []Hook
	mutation *CustomerLicenseMutation
}

// Where appends a list predicates to the CustomerLicenseDelete builder.
func (cld *CustomerLicenseDelete) Where(ps ...predicate.CustomerLicense) *CustomerLicenseDelete {
	cld.mutation.Where(ps...)
	return cld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cld *CustomerLicenseDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cld.hooks) == 0 {
		affected, err = cld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CustomerLicenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cld.mutation = mutation
			affected, err = cld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cld.hooks) - 1; i >= 0; i-- {
			if cld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cld *CustomerLicenseDelete) ExecX(ctx context.Context) int {
	n, err := cld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cld *CustomerLicenseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: customerlicense.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: customerlicense.FieldID,
			},
		},
	}
	if ps := cld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cld.driver, _spec)
}

// CustomerLicenseDeleteOne is the builder for deleting a single CustomerLicense entity.
type CustomerLicenseDeleteOne struct {
	cld *CustomerLicenseDelete
}

// Exec executes the deletion query.
func (cldo *CustomerLicenseDeleteOne) Exec(ctx context.Context) error {
	n, err := cldo.cld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{customerlicense.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cldo *CustomerLicenseDeleteOne) ExecX(ctx context.Context) {
	cldo.cld.ExecX(ctx)
}
