// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/thuanvh/golicenseserver/ent/license"
)

// License is the model entity for the License schema.
type License struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration int `json:"duration,omitempty"`
	// CPU holds the value of the "cpu" field.
	CPU int `json:"cpu,omitempty"`
	// Storage holds the value of the "storage" field.
	Storage int `json:"storage,omitempty"`
	// NumberOfNodes holds the value of the "number_of_nodes" field.
	NumberOfNodes            int `json:"number_of_nodes,omitempty"`
	customer_license_license *int
}

// scanValues returns the types for scanning values from sql.Rows.
func (*License) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case license.FieldID, license.FieldDuration, license.FieldCPU, license.FieldStorage, license.FieldNumberOfNodes:
			values[i] = new(sql.NullInt64)
		case license.FieldName:
			values[i] = new(sql.NullString)
		case license.ForeignKeys[0]: // customer_license_license
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type License", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the License fields.
func (l *License) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case license.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case license.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				l.Name = value.String
			}
		case license.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				l.Duration = int(value.Int64)
			}
		case license.FieldCPU:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cpu", values[i])
			} else if value.Valid {
				l.CPU = int(value.Int64)
			}
		case license.FieldStorage:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field storage", values[i])
			} else if value.Valid {
				l.Storage = int(value.Int64)
			}
		case license.FieldNumberOfNodes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number_of_nodes", values[i])
			} else if value.Valid {
				l.NumberOfNodes = int(value.Int64)
			}
		case license.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field customer_license_license", value)
			} else if value.Valid {
				l.customer_license_license = new(int)
				*l.customer_license_license = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this License.
// Note that you need to call License.Unwrap() before calling this method if this License
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *License) Update() *LicenseUpdateOne {
	return (&LicenseClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the License entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *License) Unwrap() *License {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: License is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *License) String() string {
	var builder strings.Builder
	builder.WriteString("License(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", name=")
	builder.WriteString(l.Name)
	builder.WriteString(", duration=")
	builder.WriteString(fmt.Sprintf("%v", l.Duration))
	builder.WriteString(", cpu=")
	builder.WriteString(fmt.Sprintf("%v", l.CPU))
	builder.WriteString(", storage=")
	builder.WriteString(fmt.Sprintf("%v", l.Storage))
	builder.WriteString(", number_of_nodes=")
	builder.WriteString(fmt.Sprintf("%v", l.NumberOfNodes))
	builder.WriteByte(')')
	return builder.String()
}

// Licenses is a parsable slice of License.
type Licenses []*License

func (l Licenses) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
