// Code generated by entc, DO NOT EDIT.

package license

const (
	// Label holds the string label denoting the license type in the database.
	Label = "license"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldCPU holds the string denoting the cpu field in the database.
	FieldCPU = "cpu"
	// FieldStorage holds the string denoting the storage field in the database.
	FieldStorage = "storage"
	// FieldNumberOfNodes holds the string denoting the number_of_nodes field in the database.
	FieldNumberOfNodes = "number_of_nodes"
	// Table holds the table name of the license in the database.
	Table = "licenses"
)

// Columns holds all SQL columns for license fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDuration,
	FieldCPU,
	FieldStorage,
	FieldNumberOfNodes,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "licenses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"customer_license_license",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(int) error
	// DefaultCPU holds the default value on creation for the "cpu" field.
	DefaultCPU int
	// DefaultStorage holds the default value on creation for the "storage" field.
	DefaultStorage int
	// DefaultNumberOfNodes holds the default value on creation for the "number_of_nodes" field.
	DefaultNumberOfNodes int
)
