// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// CustomerLicense is the predicate function for customerlicense builders.
type CustomerLicense func(*sql.Selector)

// License is the predicate function for license builders.
type License func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
